name: offsignal_workspace
description: OffSignal monorepo workspace.
publish_to: none

environment:
  sdk: ^3.12.2

workspace:
  - packages/offsignal_core
  - packages/offsignal_app
  - packages/offsignal_tools
